[package]
name = "cargo2nix"
version = "0.6.0"
edition = "2018"
license = "MIT"

[dependencies]
cargo = "0.39.0"
once_cell = "1.2.0"
pathdiff = "0.1.0"
regex = "1.3.1"
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.41"
toml = "0.5.3"
