[package]
name = "cargo2nix"
version = "0.8.1"
edition = "2018"
license = "MIT"

[dependencies]
cargo = "0.41.0"
cargo-platform = "0.1.0"
colorify = "0.2.3"
once_cell = "1.3.1"
pathdiff = "0.1.0"
regex = "1.3.1"
semver = "0.9.0"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.41"
tera = { version = "1.0.2", default-features = false }
toml = "0.5.3"
