[package]
name = "hello-world"
version = "0.1.0"
authors = ["Eyal Kalderon <eyal.kalderon@tenx.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
